[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "agent"
path = "src/main.rs"

[profile.release]
opt-level = 2

[dependencies]
rand = "0.8.4"
