name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-docker:
    name: Release Docker (${{ github.ref }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Tag on Main
        run: |
          branch=$(git branch main --contains ${{ github.ref }})
          if [ -z $branch ]; then
              echo "Tag ${{ github.ref }} is not contained in the main branch."
              exit 1
          fi

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Build NCAIC CLI Toolkit
        run: pnpm build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: ./scripts/docker_release.sh

  release-npm:
    name: Release NPM (${{ github.ref }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Tag on Main
        run: |
          branch=$(git branch main --contains ${{ github.ref }})
          if [ -z $branch ]; then
              echo "Tag ${{ github.ref }} is not contained in the main branch."
              exit 1
          fi

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: true

      - name: Build NCAIC CLI Toolkit
        run: pnpm build

      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

  release-note:
    name: Release Note (${{ github.ref }})
    runs-on: ubuntu-latest
    needs:
      - release-docker
      - release-npm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Check if Tag on Main
        run: |
          branch=$(git branch main --contains ${{ github.ref }})
          if [ -z $branch ]; then
              echo "Tag ${{ github.ref }} is not contained in the main branch."
              exit 1
          fi

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            README.md
            LICENSE
