name: Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        node:
          - "16"
          - "18"
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    name: "${{ matrix.os }} - Node.js ${{ matrix.node }}"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install esbuild for TypeScript support
        run: npm i -g esbuild && esbuild --version

      - name: Install Python 3 for Python support
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install GCC for C/C++ support
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc

      - name: Build NCAIC CLI Toolkit
        run: npx -y pnpm i && npm run build

      - name: Check NCAIC Version
        run: node dist/index.js --version

      - name: Check Language Support
        run: node dist/index.js check

      - name: Test C program
        run: node dist/index.js test programs/rand.c

      - name: Test Go program
        run: node dist/index.js test programs/rand.go

      - name: Test JS program
        run: node dist/index.js test programs/rand.js

      - name: Test PY program
        run: node dist/index.js test programs/rand.py

      - name: Test RS program
        run: node dist/index.js test programs/rand.rs

      - name: Test TS program
        run: node dist/index.js test programs/rand.ts
